/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex("events").delete();
  await knex("events").insert([
    {
      id: 1,
      name: "Hello Good Bi!",
      city: "Toronto",
      month: "July",
      day: "19",
      main_image: "https://reveal-images.s3.us-east-2.amazonaws.com/e1.jpg",
      description:
        "Join us at the cabaret, ol' chum! Come celebrate the wonderful complexities of the bi/pan/omni experience with comedy, music, and burlesque. Produced and hosted by your Holy Sparkle duo: Miss Diamond and St. Stella. Two nights with TWO unique casts!",
      venue: "The Painted Lady",
      venue_address: "218 Ossington Avenue",
      doors_time: "7:00 PM",
      start_time: "7:30 PM",
      end_time: "10:30 PM",
      organizer: "Holy Sparkles",
      ticket_prices: JSON.stringify({ advanceGA: 25, GA: 30 }),
      performers: JSON.stringify([11, 3, 1, 7, 5, 13]),
      buy_tickets: "https://plainstage.com/events/HelloGoodBiJuly19",
      gallery: JSON.stringify([]),
      posts: JSON.stringify([]),
    },
    {
      id: 2,
      name: "Hello Good Bi!",
      city: "Toronto",
      month: "July",
      day: "20",
      main_image: "https://reveal-images.s3.us-east-2.amazonaws.com/e1.jpg",
      description:
        "Join us at the cabaret, ol' chum! Come celebrate the wonderful complexities of the bi/pan/omni experience with comedy, music, and burlesque. Produced and hosted by your Holy Sparkle duo: Miss Diamond and St. Stella. Two nights with TWO unique casts!",
      venue: "The Painted Lady",
      venue_address: "218 Ossington Avenue",
      doors_time: "7:00 PM",
      start_time: "7:30 PM",
      organizer: "Holy Sparkles",
      ticket_prices: JSON.stringify({ advanceGA: 25, GA: 30 }),
      performers: JSON.stringify([7, 4, 1, 6, 9]),
      buy_tickets: "https://plainstage.com/events/HelloGoodBiJuly20",
      gallery: JSON.stringify([]),
      posts: JSON.stringify([]),
    },
    {
      id: 3,
      name: "Bad Cabaret",
      city: "Toronto",
      month: "July",
      day: "20",
      main_image: "https://reveal-images.s3.us-east-2.amazonaws.com/e3.jpg",
      description:
        "A queer cabaret where every unique act appears one time only. Alt Comedy, Stand-Up, Drag, Burlesque, Art, Music, Live Looping, and more!\n\nThe heat is on, the fiery sun is melting the tarmac, and Toronto's only live entertainment is back for a sweaty, unhinged July blowout. You'll laugh, you'll cry, you'll see queer people do weird, incredible things you've never seen before.\n\nEvery act is one-of-a-kind and one-time only. BAD CABARET hosts stange and novel acts of all persuasions, every third week of the month at Sweet Action Theatre.\nFollow @baddmachine on Instagram for lineup announcements.",
      venue: "Sweet Action Theatre",
      venue_address: "180 Shaw Street",
      doors_time: "7:00 PM",
      start_time: "7:30 PM",
      organizer: "James Jordan",
      ticket_prices: JSON.stringify({ GA: 20 }),
      performers: JSON.stringify([11, 10, 1, 3, 13, 4, 7]),
      buy_tickets:
        "https://www.eventbrite.ca/e/bad-cabaret-summer-madness-tickets-941598144397?utm-campaign=social&utm-content=attendeeshare&utm-medium=discovery&utm-term=listing&utm-source=cp&aff=ebdsshcopyurl",
      gallery: JSON.stringify([]),
      posts: JSON.stringify([]),
    },
    {
      id: 4,
      name: "Decadence & Dishes: A Burlesque Feast",
      city: "Toronto",
      month: "July",
      day: "25",
      main_image: "https://reveal-images.s3.us-east-2.amazonaws.com/e4.jpg",
      description:
        "Indulge in an evening of sensual entertainment and culinary delights at Decadence & Dishes: A Burlesque Feast. Our tantalizing burlesque performers will whisk you away on a journey of seductive dance, playful tease, and mesmerizing charm, all while you savor a sumptuous summer menu crafted by our master chef. This unique fusion of gourmet dining and captivating burlesque promises an unforgettable night of indulgence and delight. Each ticket includes a $40 food voucher to enjoy from either the menu or the bar! Join us for a night where the art of burlesque meets the art of cuisine,and let Decadence & Dishes: A Burlesque Feast be your most delicious and dazzling night out this summer.",
      venue: "MY HOUSE",
      venue_address: "2882 Dundas Street West",
      doors_time: "6:00 PM",
      start_time: "9:00 PM",
      end_time: "11:00 PM",
      organizer: "Mayfly Creative Productions",
      ticket_prices: JSON.stringify({ GA: 65 }),
      performers: JSON.stringify([6, 10, 12, 2]),
      buy_tickets:
        "https://www.eventbrite.ca/e/decadence-dishes-a-burlesque-feast-studio-54-tickets-922367234227?utm-campaign=social&utm-content=attendeeshare&utm-medium=discovery&utm-term=listing&utm-source=cp&aff=ebdsshcopyurl",
      gallery: JSON.stringify([]),
      posts: JSON.stringify([]),
    },
    {
      id: 5,
      name: "Rouge Studio of Dance Showcase",
      city: "Toronto",
      month: "July",
      day: "27",
      main_image: "https://reveal-images.s3.us-east-2.amazonaws.com/e5.jpg",
      description:
        "Join us for the VERY FIRST Rouge Studio of Dance Toronto Student Showcase! Featuring the first graduating Level 3 Burlesque class, witness the exciting debuts of 6 new burlesque artists as we celebrate Rouge's first year in Toronto! Drinks will be available for purchase! There will be gogo so tipping is welcomed during their set. We will also have studio merch for sale. Please let the organizer know if you require accessibility seating Tickets are final sale and non-refundable. 19+ event. Get your tickets today, this event is not to be missed!",
      venue: "Super Wonder Gallery",
      venue_address: "1162 Bloor Street West",
      doors_time: "8:00 PM",
      start_time: "9:00 PM",
      end_time: "11:00 PM",
      organizer: "Rouge School of Dance",
      ticket_prices: JSON.stringify({ GA: 23 }),
      performers: JSON.stringify([8, 13, 5, 2]),
      buy_tickets:
        "https://www.eventbrite.ca/e/rouge-studio-of-dance-showcase-toronto-tickets-916851667017?utm-campaign=social&utm-content=attendeeshare&utm-medium=discovery&utm-term=listing&utm-source=cp&aff=ebdsshcopyurl",
      gallery: JSON.stringify([]),
      posts: JSON.stringify([]),
    },
    {
      id: 6,
      name: "Kulture Fest Cabaret",
      city: "Toronto",
      month: "July",
      day: "28",
      main_image: "https://reveal-images.s3.us-east-2.amazonaws.com/e6.jpg",
      description:
        "It's another Kreative Kulture Summer street festival themed show, Kukture Fest 2024 is near. All kinds of summer festival vibes. Drag and Burlesque with festival themes such as CNE, Jazz Fest, Caribana, Pride, Salsa on St.Clair and more...",
      venue: "TacoTaco",
      venue_address: "319 Augusta Avenue",
      doors_time: "8:00 PM",
      start_time: "8:45 PM",
      organizer: "Kage Wolfe",
      ticket_prices: JSON.stringify({
        advanceGA: 23,
        GA: 28,
        tableDiscounts: true,
      }),
      performers: JSON.stringify([]),
      buy_tickets:
        "https://www.eventbrite.ca/e/kulture-fest-cabaret-tickets-936974013497?utm-campaign=social&utm-content=attendeeshare&utm-medium=discovery&utm-term=listing&utm-source=cp&aff=ebdsshcopyurl",
      gallery: JSON.stringify([]),
      posts: JSON.stringify([]),
    },
    {
      id: 7,
      name: "The Thick, Fat, Juicy, and Naked Show",
      city: "Toronto",
      month: "August",
      day: "2",
      main_image: "https://reveal-images.s3.us-east-2.amazonaws.com/e7.jpg",
      description:
        "A platform for big queer BIPOC bodies to take up space, perform, strip and get naked! This is a seated 90 min show with one intermission. Audience games at intermission with prizes from Model Express for Best Dressed and Best Ass Shaker",
      venue: "The Assembly Theatre",
      venue_address: "1479 Queen Street W",
      doors_time: "9:15 PM",
      start_time: "9:30 PM",
      end_time: "11:00 PM",
      organizer: "Gushy",
      ticket_prices: JSON.stringify({ GA: 28, VIP: 33 }),
      performers: JSON.stringify([12, 2, 11, 6, 9]),
      buy_tickets:
        "https://www.eventbrite.ca/e/the-thick-fat-juicy-and-naked-show-tickets-942754643517?utm-campaign=social&utm-content=attendeeshare&utm-medium=discovery&utm-term=listing&utm-source=cp&aff=ebdsshcopyurl",
      gallery: JSON.stringify([]),
      posts: JSON.stringify([]),
    },
    {
      id: 8,
      name: "Breaking the Borders Benefit",
      city: "Toronto",
      month: "August",
      day: "10",
      main_image: "https://reveal-images.s3.us-east-2.amazonaws.com/e8.jpg",
      description:
        "Hey hey hey, here we go again, this year we throwing the house out the window with an amazing, raw, loud and self-managed/DIY line up, y'all will find some familiar names and faces (what we call the local fam) plus some crazy maniac bands coming to visit from out of town and out the country. This year learning from prior experiences, we decided to have 4 different shows within the celebration of the fest, 3 main shows and 1 free “street” matinee show reclaiming back spaces like the Kensington Market. Let's make this happen one more time, let’s try and make it more diverse every year, let’s remind everyone that NO ONE IS ILEGAL ON STOLEN LAND, and that revolution will only be possible if we all the oppressed come together. That being said, keep yourself and your homies safe and let’s break some damned borders with anti-systemic/anti-fascist noise. 'Es necesario hacer un mundo nuevo, un mundo donde quepan muchos mundos, un mundo donde quepan todos los mundos.' -Proverbio Zapatista",
      venue: "Lee's Palace",
      venue_address: "529 Bloor Street W",
      start_time: "2:00 PM",
      end_time: "11:00 PM",
      organizer: "Dirty Bird",
      ticket_prices: JSON.stringify({ GA: 20 }),
      performers: JSON.stringify([3, 8, 12, 4]),
      buy_tickets: null,
      gallery: JSON.stringify([]),
      posts: JSON.stringify([]),
    },
    {
      id: 9,
      name: "The Sugar Shack",
      city: "Toronto",
      month: "August",
      day: "10",
      main_image: "https://reveal-images.s3.us-east-2.amazonaws.com/e9.jpg",
      description:
        "The Sugar Shack is back at Junction Underground. Join us for an energetic, warm, friendly and inclusive show in an intimate venue. Join us for a fun and flirty evening of burlesque in this intimate venue. The performances will showcase the breadth of the burlesque artform from classic to comedy and everything in-between.",
      venue: "Junction [City] Underground",
      venue_address: "2907 Dundas W",
      doors_time: "8:00 PM",
      start_time: "9:00 PM",
      organizer: "Sugar Holiday",
      ticket_prices: JSON.stringify({ advanceGA: 23, GA: 30 }),
      performers: JSON.stringify([13, 5, 6, 2]),
      buy_tickets:
        "https://www.eventbrite.com/e/the-sugar-shack-a-burlesque-show-tickets-923882315877?utm-campaign=social&utm-content=attendeeshare&utm-medium=discovery&utm-term=listing&utm-source=cp&aff=ebdsshcopyurl",
      gallery: JSON.stringify([]),
      posts: JSON.stringify([]),
    },
  ]);
}

/* COPY ME
 {
      id: ,
      name: "", 
      city: "Toronto",
      month: "July",
      day: "",
      main_image: "https://reveal-images.s3.us-east-2.amazonaws.com/e1.jpg",
      description:
        "",
      venue: "",
      venue_address: "",
      doors_time: ":00 PM",
      start_time: ":00 PM",
      end_time: ":00 PM",
      producer: "",
      ticket_prices: JSON.stringify({  }),
      performers: JSON.stringify([]),
      buy_tickets: "",
      gallery: JSON.stringify([]),
      posts: JSON.stringify([]),
    },
    */
